# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  lane :beta do
    # ...
  
    firebase_app_distribution(
      app: "1:996930607037:android:f6e5abf658ab7f248d64d4",
      testers_file: "app_testers.txt",
      android_artifact_path: "C:/Users/Owner/Desktop/GridUIImplementation/build/app/outputs/flutter-apk/app-release.apk"
    )
    # ...
  end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
